CREATE TABLE `Ads` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `location` TEXT, `title` VARCHAR(255), `url` VARCHAR(255), `imageUrl` VARCHAR(255), `active` TINYINT(1) DEFAULT 1, `order` INTEGER DEFAULT 0, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);

CREATE TABLE `Suppliers` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `name` VARCHAR(255) NOT NULL, `email` VARCHAR(255), `phone` VARCHAR(255), `address` TEXT, `acceptedTnC` TINYINT(1) DEFAULT 0, `metadata` JSON, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);

CREATE TABLE `Categories` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `name` VARCHAR(255) NOT NULL, `icon` VARCHAR(255) DEFAULT '📦', `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);

CREATE TABLE `Products` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `title` VARCHAR(255) NOT NULL, `description` TEXT, `price` FLOAT NOT NULL, `isService` TINYINT(1) DEFAULT 1, `deliveryAvailable` TINYINT(1) DEFAULT 1, `metadata` JSON, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `SupplierId` INTEGER REFERENCES `Suppliers` (`id`) ON DELETE SET NULL ON UPDATE CASCADE, `CategoryId` INTEGER REFERENCES `Categories` (`id`) ON DELETE SET NULL ON UPDATE CASCADE);

CREATE TABLE `Orders` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `customerName` VARCHAR(255), `customerPhone` VARCHAR(255), `customerAddress` TEXT, `type` TEXT, `totalAmount` FLOAT, `platformFee` FLOAT, `status` TEXT DEFAULT 'created', `paymentInfo` JSON, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `SupplierId` INTEGER REFERENCES `Suppliers` (`id`) ON DELETE SET NULL ON UPDATE CASCADE, `ProductId` INTEGER REFERENCES `Products` (`id`) ON DELETE SET NULL ON UPDATE CASCADE);

CREATE TABLE `AnalyticsVisits` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `path` VARCHAR(255), `referrer` VARCHAR(255), `ip` VARCHAR(255), `userAgent` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);

